name: monai
channels:
  - defaults
dependencies:
  - python=3.10
  - pip:
    - wheel==0.42.0
    - boto3
    - pandas
    - python-dotenv
    - fastapi==0.100.0
    - uvicorn==0.22.0
    - termcolor==2.3.0
